name: Build plugin

on:
  push:
    tags:
      - '*'

env:
  PLUGIN_NAME: logseq-live-math

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: true

      - name: Build
        id: build
        run: |
          pnpm build
          mkdir ${{ env.PLUGIN_NAME }}
          cp -r README.md LICENSE dist index.html package.json icon.svg ${{ env.PLUGIN_NAME }}
          tag_name=$(git tag --sort version:refname | tail -n 1)
          zip -r ${{ env.PLUGIN_NAME }}-${tag_name}.zip ${{ env.PLUGIN_NAME }}
          echo "tag_name=$tag_name" >> "$GITHUB_OUTPUT"

      - name: Generate Changelog
        uses: orhun/git-cliff-action@v2
        id: changelog
        with:
          args: --latest

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.changelog.outputs.content }}
          files: |
            ${{ env.PLUGIN_NAME }}-*.zip
            package.json
